apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service5
  description: Order processing microservice for the TechCorp e-commerce platform. Handles order creation, status tracking, and fulfillment integration.
  annotations:
    github.com/project-slug: samgabrail/service5
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: service5
  tags:
    - nodejs
    - gitops
spec:
  type: service
  lifecycle: production
  owner: group:default/developers
  system: system:default/customer-portal
